CREATE TABLE VEHICLES (
VEHICLEID VARCHAR(40) NOT NULL PRIMARY KEY,
VEHICLEMAKE VARCHAR(20) NOT NULL,
VEHICLEMODEL VARCHAR(20) NOT NULL,
VEHICLEREGISTRATION VARCHAR(15) NOT NULL
);

CREATE TABLE CUSTOMERS (
CUSTOMERID VARCHAR(40) NOT NULL PRIMARY KEY,
CUSTOMERFIRST VARCHAR(20) NOT NULL,
CUSTOMERLAST VARCHAR(20) NOT NULL,
CUSTOMERPHONE VARCHAR(15) NOT NULL
);

CREATE TABLE NCTBOOKINGS (
NCTBOOKINGID SERIAL NOT NULL PRIMARY KEY,
NCTBOOKINGCUSTOMERFIRST VARCHAR(40) NOT NULL,
NCTBOOKINGCUSTOMERLAST VARCHAR(40) NOT NULL,
NCTBOOKINGVEHICLEID VARCHAR(40) NOT NULL,
NCTBOOKINGDATE VARCHAR(15) NOT NULL,
NCTBOOKINGLOCATION VARCHAR(40) NOT NULL,
NCTBOOKINGSTATUS VARCHAR(40) NOT NULL
);